return {
  { -- Set treesitter parsers
  'nvim-treesitter/nvim-treesitter',
  opts = {
      ensure_installed = {
          'bash',
          'css',
          'diff',
          'dockerfile',
          'go',
          'html',
          'ini',
          'java',
          'javascript',
          'json',
          'json5',
          'jsonc',
          'jsonnet',
          'kotlin',
          'lua',
          'make',
          'markdown',
          'markdown_inline',
          'promql',
          'proto',
          'python',
          'regex',
          'rego',
          'ruby',
          'rust',
          'scala',
          'sql',
          'terraform',
          'toml',
          'tsx',
          'typescript',
          'vim',
          'yaml',
      },
    },
  },
}